### ISSUE TITLE
no way to delete a patchset?

### ISSUE THREAD

**Issue by jeisinger** [esprehn/chromium-codereview#114]
Or maybe I just don't see it

**Comment by esprehn** [comment]
There isn't, why do you want to do that?

**Comment by jeisinger** [comment]
the specific example when I filed this bug was:

I uploaded a patchset A, got reviewer comments
addressed them in patchset B
reviewer decided that A was better and lgtm'd that

what I wanted to do then was delete B, hit the commit button

**Comment by esprehn** [comment]
Fixed by https://codereview.chromium.org/873593007
