### ISSUE TITLE
Code review does not display preview of binary files

### ISSUE THREAD

**Issue by sdefresne** [esprehn/chromium-codereview#115]
See https://codereview.chromium.org/771723002 where I'm adding png/jpg/webp images. I cannot find a way to preview the new images in the code review tool.

**Comment by esprehn** [comment]
png works, but it's the only format right now. Just need to expand the extension list.

https://github.com/esprehn/chromium-codereview/blob/e4813f1c8cc5b25e383e028a359f035f0dbfd779/ui/diff_parser.js#L176

**Comment by esprehn** [comment]
Fixed by https://codereview.chromium.org/904253002
