### ISSUE TITLE
Change list should list files in alphabetic order

### ISSUE THREAD

**Issue by sdefresne** [esprehn/chromium-codereview#121]
Files seems to be in a random order (see for example last patch of https://codereview.chromium.org/777863002).

Order is:
components/autofill/core/browser/autocomplete_history_manager_unittest.cc
components/components.gyp
components/autofill/core/browser/DEPS
...

This does not make any sense.

**Comment by esprehn** [comment]
Yeah PatchFile.compare is busted, need to come up with a better way to do this fancy sorting.

**Comment by esprehn** [comment]
Fixed by https://codereview.chromium.org/992403002
