### ISSUE TITLE
Font used for diff on OS X (Yosemite) is non-monospaced

### ISSUE THREAD

**Issue by sdefresne** [esprehn/chromium-codereview#122]
Look at patch 4 of components/translate/ios/browser/js_translate_manager.h in issue https://codereview.chromium.org/809693003/ on OS X (Yosemite) and the colon appears non-aligned.

When inspecting the element, the font-family is set to "Monaco, monospaced". If I manually change the font-family to "monospaced" then the colon are correctly aligned. It appears that the "Monaco" font that is available on OS X (Yosemite) is not correctly monospaced.

I would recommend "Menlo" which is the default monospace font on OS X (used by Terminal and Xcode by default).

**Comment by esprehn** [comment]
Monaco is also monospace, it just doesn't handle bold properly. I had fixed this, but when we switched to the third_party CSS files my modifications were undone.

Should be fixed by https://codereview.chromium.org/896313003
