### ISSUE TITLE
File comment should be visible

### ISSUE THREAD

**Issue by sdefresne** [esprehn/chromium-codereview#127]
The old UI of the review system allowed to add file level comment (i.e. comment on the file, not a particular line). The new UI does not display those comments inline. It just leave a mark there is a comment on the file, but when you expand it, you cannot see it.

See for example https://codereview.chromium.org/813503003/

**Comment by esprehn** [comment]
I'm not aware of file level comments in the old UI, but there are comments outside the diff range there. They won't show up until you expand context.
