### ISSUE TITLE
Need a way to share links with users not on the extension

### ISSUE THREAD

**Issue by ojanvafai** [esprehn/chromium-codereview#17]
1. So there an easy way to get there
2. So there's an easy thing to copy-paste when sharing review links.

**Comment by esprehn** [comment]
What are you going back to the old tool for? Sharing links is important, but I'd like to track which features have you going back as well.

**Comment by ojanvafai** [comment]
I'm filing bugs for all the things I go back for. Sharing links is my main need here.
