### ISSUE TITLE
chromiumcodereview.appspot.com doesn't redirect

### ISSUE THREAD

**Issue by ojanvafai** [esprehn/chromium-codereview#22]
e.g. https://chromiumcodereview.appspot.com/319283002/ goes to the old review tool.

**Comment by esprehn** [comment]
That was on purpose, why do we have the code review app on multiple domains? We should just fix app engine to redirect chromiumcodereview.appspot.com to codereview.chromium.org.

**Comment by ojanvafai** [comment]
I agree its silly, but it doesn't seem like a fight worth fighting. Easy enough to workaround, no?
