### ISSUE TITLE
view-source: urls of codereview get redirected back

### ISSUE THREAD

**Issue by chrishtr** [esprehn/chromium-codereview#26]
It looks like the regexp may be too broad for the extension?

**Comment by esprehn** [comment]
The regex is fine, this is a problem with extensions in general. The extension can't tell that a navigate is to a view-source page. I'm not actually sure how to fix this. Maybe @abarth knows?

**Comment by abarth** [comment]
Dunno

**Comment by ojanvafai** [comment]
Meh. I'd put this on the list of things that will get fixed when we make this part of rietveld proper. Not worth fixing.

**Comment by esprehn** [comment]
This is sort of fixed by https://github.com/esprehn/chromium-codereview/commit/996bf87cbc74e478581abc1b629bb5796446646e

Now you can see view-source:, but it just shows you the 404 page. I don't think we can do any better until it's not inside an extension.
