### ISSUE TITLE
Typing "m" should bring up the "Publish" dialog

### ISSUE THREAD

**Issue by abarth** [esprehn/chromium-codereview#34]
I'm not sure if you want to support all the keyboard shortcuts that Rietveld supported, but the one I miss the most is being about to type "m" anywhere in the middle of a review and get the "publish" dialog.

**Comment by ojanvafai** [comment]
Some discussion of this on https://github.com/esprehn/chromium-codereview/issues/3.

I also agree that we shouldn't do all the keyboard shortcuts and that m is particulary useful.

Although, if we had a UI like the webkit one where the overall comments box and the publish button were always show fixed to the bottom of the window, then we wouldn't need the keyboard shortcut. :)

**Comment by abarth** [comment]
Closing as duplicate of #3
