### ISSUE TITLE
Refreshing the "My Issues" page is weird

### ISSUE THREAD

**Issue by abarth** [esprehn/chromium-codereview#37]
Support I have the "My Issues" page open.  How do I refresh it?  It seems like I first need to reload the page, wait, and then click the "Refresh" link.  It would be nice to be able to refresh the page with one click (either by clicking the browser's reload button or by having the app's refresh link visible somewhere).

**Comment by esprehn** [comment]
Yeah this is weird. I did it since it makes the issue list so much faster. Perhaps I should only cache in the back button case, but not in the initial load case. Then refresh works as expect, it's just 4 seconds slower.
