### ISSUE TITLE
Configure a list of rietveld URLs

### ISSUE THREAD

**Issue by nodirt** [esprehn/chromium-codereview#40]
Hi,

Feature request: allow a user to configure the list of websites where the new UI gets applied.

codereview.chromium.org is not the only one.

Thanks!

**Comment by aarongable** [comment]
This can be hard, as allowing a fully-configurable set of URLs requires requesting the permission to have access to every URL ever. Which is unfortunate.

But at the least, this should apply to "codereview.appspot.com", where Rietveld itself is reviewed :)

**Comment by ojanvafai** [comment]
If someone can help expose the JSON APIs that the extension needs, I imagine we could just drop the extension code into reitveld and not having to do any of this extension stuff.
