### ISSUE TITLE
Issues don't load until tab is focused

### ISSUE THREAD

**Issue by zetafunction** [esprehn/chromium-codereview#41]
1. Open a bunch of issues in the background (ctrl+click a bunch of issues in the overview).
2. Observe they don't load until the tab is focused.

**Comment by esprehn** [comment]
This is polymer listening inside requestAnimationFrame to startup. There's nothing I can do unfortunately.

**Comment by esprehn** [comment]
I'm wrong, this is because I'm using this.async() inside the <cr-view> routing system, which defaults to raf if you don't pass a time. Since raf doesn't fire on background tabs the view system never bootstraps.
