### ISSUE TITLE
Columns aren't aligned across sections in inbox view

### ISSUE THREAD

**Issue by aarongable** [esprehn/chromium-codereview#44]
The columns of the inbox view (issue number, owner, subject, date, and status) are right/left justified within each section (drafts, outgoing, unsent, incoming). It would improve readability if the columns were consistent widths across all inbox sections.

![image](https://cloud.githubusercontent.com/assets/2474926/3264467/831c5d56-f27f-11e3-855b-d049af287ee7.png)

**Comment by esprehn** [comment]
This is difficult with CSS unless you put both the headers and the rows into one massive table which sucks. I guess I could make the owner field fixed width and truncate the names...

**Comment by aarongable** [comment]
If you use fixed-width columns, won't long usernames (which are generally not a single token) wrap, just like long issue subjects?
