### ISSUE TITLE
"Patchsets" is too close (and may overlap) to the issue metadata when the description is short

### ISSUE THREAD

**Issue by phistuck** [esprehn/chromium-codereview#46]
Examples -
https://codereview.chromium.org/331943004 (too close)
https://codereview.chromium.org/336903002 (ovelaps)

The display: flex; element does not contain the full height of its contents. Is this an issue with the coded CSS or is it a Blink issue?

Also, why bother using a div with display: table, display: table-row and display: table-cell instead of an actual table? What do you gain by that?

**Comment by ojanvafai** [comment]
I also don't see the bug. What Chrome are you in? We had some flexbox bugs that could explain this if you're in an older Chrome.

**Comment by phistuck** [comment]
I am using Chrome 35. Using the latest 64 bit canary - it does seem fixed.

**Comment by ojanvafai** [comment]
Yeah. There's a bunch of known issues with the tool in 35. Not worth fixing since 36 will be pushed to stable soon enough.
