### ISSUE TITLE
Add the "Base URL" field

### ISSUE THREAD

**Issue by phistuck** [esprehn/chromium-codereview#47]
It is very useful when generally sifting through issues and finding out whether this is a Chromium issue, a Blink issue, a Dart issue and so on.

Thank you!

**Comment by aarongable** [comment]
The CQ and Rietveld are transitioning away from using the Base URL field and replacing it with a "Project" field, which more accurately represents the human concept of a project (chromium blink, etc.). That transition will hopefully be complete in a week or two. So just as an FYI, really.

**Comment by phistuck** [comment]
Thank you. :)
