### ISSUE TITLE
Make clickable elements and links targetable

### ISSUE THREAD

**Issue by aarongable** [esprehn/chromium-codereview#54]
I use Vimium, and none of the click targets (including the ones that seem like real links, like reviewer names) are targetable by the link-following shortcut. I'm sure I'm a corner case, but it would be really nice if this worked. And it seems like this might lead to other accessibility issues too, though I'm not sure.

**Comment by esprehn** [comment]
Reviewer names are real links. I think your extension just doesn't understand Shadow DOM.
