### ISSUE TITLE
Allow viewing patches without being logged in.

### ISSUE THREAD

**Issue by dj2** [esprehn/chromium-codereview#60]
I often try to view patches in a profile that isn't logged into the code review tool. I have to either switch profiles or disable the extension to view the CL.

It would be nice if I could view the CL, just not be able to comment, if not logged in.

**Comment by esprehn** [comment]
Why not just login?

**Comment by dj2** [comment]
Because I don't want to login to my chromium account in my google profile. And, I really don't want to log into codereview as my google account as I end up leaving comments from the wrong account.

**Comment by esprehn** [comment]
I'll see when I can get to this. Unfortunately it really complicates the app to support both signed in and signed out modes. I just use multi login to be in @chromium.org and @google.com at the same time.
