### ISSUE TITLE
Improve the performance of cr-diff.emitLine

### ISSUE THREAD

**Issue by esprehn** [esprehn/chromium-codereview#63]
When loading patch diffs very little time is inside the DiffParser, it's almost all inside &lt;cr-diff&gt;'s emitLine which breaks down as:

63% set className
11% syntax highlighting
8% set innerHTML [1]
7% createElement
5% appendChild
1% set textContent

(according to the Profile tab in the inspector).

[1] The innerHTML is adding the output of the syntax highlighter.

It's very surprising that setting className is so expensive.

**Comment by ojanvafai** [comment]
Have you measured total runtime with and without the inspector open? I wonder if the inspector is skewing the performance numbers again.

**Comment by esprehn** [comment]
Having looked closer at this and benchmarked, 50% of the time is inside hljs.highlight() for large diffs, className doesn't appear to matter at all. The rest of the time is just script running, and createElement calls. There's nothing obvious to optimize besides storing the syntax highlights on the server like Rietveld did.

I think we should call this fixed for now.
