### ISSUE TITLE
Missing "Download [raw] [tar.bz2]" features of rietveld in ChromeReview

### ISSUE THREAD

**Issue by vivekgalatage** [esprehn/chromium-codereview#67]
I usually do:

`curl https://codereview.chromium.org/download/issue325663002_1.diff | git apply`

by copying the URL of raw download link.

It would be really handy to have these links with the ChromeReview as well.

**Comment by esprehn** [comment]
Why not use git cl patch {issueId} ?

**Comment by vivekgalatage** [comment]
Yes, indeed thats what I do most of the time. 

Sometimes, when I am working with in-flight patches which are not ready or by someone else, I just want to play quickly with them. In that, I wouldn't create a separate branch (`git cl patch` commits locally. With -n option it applies to the index).

Its just a convinient developer workflow. 

Thoughts?

**Comment by esprehn** [comment]
Fixed by https://github.com/esprehn/chromium-codereview/commit/572b62b40845d5354ef68109d08bc50755a7253f
