### ISSUE TITLE
Unsubscribe from issue

### ISSUE THREAD

**Issue by natduca** [esprehn/chromium-codereview#72]
I end up with ancient issues that are so old they're useless, but I can't close them. Now, every few months, I manually open each one, then edit it to remove my name from the cc and reviewers list. Would be awesome if it was more automagical. :)

**Comment by esprehn** [comment]
Why can't you close them?

**Comment by natduca** [comment]
There are people out there who like to keep codereviews around in case they get back to them. I've tried in the past to close them, and I do when possible, but even so, I had ~50 backlogged that I couldn't actually close because people either complained when I did, or I knew up front they wouldn't want them closed. The way to deal with this is to unsub from them.

**Comment by esprehn** [comment]
I think this might be better solved by #73. I'll think about adding such an action though.

**Comment by natduca** [comment]
That'd be a great first order feature, yeah!

**Comment by esprehn** [comment]
Given the date range filtering, do you still find you want to do this @natduca ?

**Comment by natduca** [comment]
Naw the way you did it was brilliant. I love it.
