### ISSUE TITLE
Add a little more space at the bottom of the screen.

### ISSUE THREAD

**Issue by dj2** [esprehn/chromium-codereview#74]
The URL popup at the bottom of the screen just overlaps the last closed code review. Would be nice if there was a few pixels of space between the two, I keep thinking there is another entry at the bottom that is being covered.

**Comment by esprehn** [comment]
Sigh, that unbalances the whitespace around the page. Chrome's status bar is stupid because it forces page authors to account for the fact that it takes up space over the content.
