### ISSUE TITLE
Change colour of headers in diff when expanded.

### ISSUE THREAD

**Issue by dj2** [esprehn/chromium-codereview#75]
When you expand out a series of diffs it can be hard to pick out the separation between each file, the line showing the filename and other information is the same colour as the diffs.

Would be nice if those could be turned a different colour like black so it's easier to see the file boundaries when reading through a diff.

**Comment by ojanvafai** [comment]
I also find myself confused by a diff only to find that I had scrolled to a new file without realizing it.
