### ISSUE TITLE
My issues screen shows buggy "last modified" time

### ISSUE THREAD

**Issue by mounirlamouri** [esprehn/chromium-codereview#77]
For example, I can see this:
"360493003 - Re-enable screen_orientation/ tests following mock fixes. - 15 hours ago"

If I click there, I get the CL view which shows me a more realistic last modified time:
Created: Jun 27th 2014 2:13pm
Modified:   Jun 27th 2014 2:13pm
And the comment has: "25 minutes ago"

I wonder if that could be a timezone issue.

**Comment by esprehn** [comment]
That's possible, what time zone are you in?

**Comment by esprehn** [comment]
Closing this until there's a repro.
