### ISSUE TITLE
Publishing comments with 'm' doesn't seem to include individual line comments

### ISSUE THREAD

**Issue by natduca** [esprehn/chromium-codereview#78]
i added line by line comments
then i think i pressed 'm' to say lgtm

this posted this:
 https://codereview.appspot.com/106450045/#msg4

but did'nt include comments until i then sent things again?
  https://codereview.appspot.com/106450045/#msg6

not sure exactly what i did wrong...

**Comment by esprehn** [comment]
Sounds like a rietveld bug? It definitely does do that. Can you try again?

**Comment by natduca** [comment]
lets wontfix till i have a hard repro.. i've not seen it happen this week so fingers crossed?

**Comment by natduca** [comment]
Aha, I have the repro: if you have a draft comment [eg you didn't press save], then you press 'publish' then it sends the saved comments but not the drafts.

Repro steps:
1. click a line to add feedback. write a bit. Do not press save.
2. publish comments.

Expected behavior: tool complains that there unsent drafts.
Actual behavior: the unsent draft is lost, and the message is posted with the comments that were saved.

**Comment by esprehn** [comment]
Filed a new bug https://github.com/esprehn/chromium-codereview/issues/87
