### ISSUE TITLE
Way to download/get link to raw patch for a given patchset

### ISSUE THREAD

**Issue by natduca** [esprehn/chromium-codereview#79]
The regular codereview UI has lnks to the raw patchset in case you want to download it, apply it, etc. Right now I'm disabling the extension in order to get them hehe.

**Comment by dj2** [comment]
If you want to apply the patch you can create a branch and do 'git cl patch <issue number>' and that will attempt to patch the CL directly into your branch.

**Comment by esprehn** [comment]
@natduca Why not do "git cl patch {issueId}" ?

**Comment by natduca** [comment]
Raw patches are useful when you intend to edit it before applying the patch.

Also, I use this for downloading old patch sets, not the current one.
