### ISSUE TITLE
Cache issues previously seen

### ISSUE THREAD

**Issue by zetafunction** [esprehn/chromium-codereview#8]
I have a tendency to open and close Rietveld a lot, and with the extension, that means I see 'loading issues' a lot. It'd be nice if there was an initial list of cached issues that the extension saw last time while 'loading issues' is in progress. The main problem I see is if the list did change, you'd probably have to have the user explicitly acknowledge that they wanted to update the list. Otherwise, the issue list might shift out from under the user while trying to interact with it.

**Comment by esprehn** [comment]
Without the extension you'd see a white page a lot. :) But yeah I need some kind of caching since Rietveld takes 3s to load that page. Ideally we'd get a better JSON API that was much faster.

**Comment by ojanvafai** [comment]
+1 to just exposing a Rietveld API for this. Wait...I'm confused, there is an API for this already! The review tool that @abarth and I wrote used it. I don't remember exactly what it was. I think I used the search form. It's not perfect because you need to do a couple requests to get all the cases you care about, but I bet it'd be much faster.

**Comment by ojanvafai** [comment]
The search page takes a format=json parameter: https://github.com/abarth/codereview/blob/master/components/rietveld-issuelist.html

**Comment by ojanvafai** [comment]
Also, the requests are _much_ faster if you put a limit on the number of issues.

This takes 0.5 seconds for me:
https://codereview.chromium.org/search?closed=3&reviewer=ojan@chromium.org&format=json&limit=10

This takes 4 seconds:
https://codereview.chromium.org/search?closed=3&reviewer=ojan@chromium.org&format=json&limit=100

**Comment by esprehn** [comment]
I can't show "Issues with drafts" if I do that. What's more important?
