### ISSUE TITLE
Support non-Chromium projects in BUG= line

### ISSUE THREAD

**Issue by ajklein** [esprehn/chromium-codereview#83]
For example, `BUG=v8:3291` should link to https://code.google.com/p/v8/issues/detail?id=3291. Looks like this would be a simple change to [`<cr-linkified-text>`](https://github.com/esprehn/chromium-codereview/blob/master/ui/components/cr-linkified-text.html)

**Comment by esprehn** [comment]
Good catch, it looks like rieveld has this:

```
def replace_bug(message):
  bugs = re.split(r"[\s,]+", message.group(1))
  base_tracker_url = 'http://code.google.com/p/%s/issues/detail?id=%s'
  valid_trackers = ('chromium', 'chromium-os', 'chrome-os-partner', 'gyp',
                    'skia', 'v8')
```
