### ISSUE TITLE
Inexistent patch chunk with extension

### ISSUE THREAD

**Issue by jchaffraix** [esprehn/chromium-codereview#88]
The first diff on line 1 ('1' added) doesn't exist if you don't use the extension on patchset 1 of:

https://codereview.chromium.org/426373002/

**Comment by esprehn** [comment]
Yes it does:

https://codereview.chromium.org/426373002/diff/1/content/child/runtime_features.cc

**Comment by esprehn** [comment]
Also see the raw diff, you definitely added that 1:

https://codereview.chromium.org/download/issue426373002_1.diff
