### ISSUE TITLE
"edit" link for CL description is off-screen to the right.

### ISSUE THREAD

**Issue by chrishtr** [esprehn/chromium-codereview#94]
Instead it needs to be vertically aligned with the "Settings" link in the top bar.

**Comment by esprehn** [comment]
Have an example link? I don't see that.

**Comment by chrishtr** [comment]
It happens for e.g. https://codereview.chromium.org/520803004/ (but any
code review). On 38.0.2125.0 (dev). Maybe it's a Chrome bug? The reviewer
emails also have no space between them in the layout.

**Comment by esprehn** [comment]
This was vulcanizer, I was passing --strip which removed all the whitespace and broke things. I've turned that off for now. Fixed by https://github.com/esprehn/chromium-codereview/commit/61ef3f6011af1f7bbcf7c8bd66bd72aecb127f72
