### ISSUE TITLE
No space between users in cc/reviewer list

### ISSUE THREAD

**Issue by jeisinger** [esprehn/chromium-codereview#97]
e.g. on https://codereview.chromium.org/292173002/ there are no spaces between the reviewers, instead it shows meeseidelharakenhorokcckinukonasko

**Comment by esprehn** [comment]
This was fixed by https://github.com/esprehn/chromium-codereview/commit/61ef3f6011af1f7bbcf7c8bd66bd72aecb127f72

I updated the extension Friday, not sure why you didn't get the update yet. 0.47 should be fixed.
