### ISSUE TITLE
Title showing as "404 Not Found" in chrome 37.0.2062.94 on Linux

### ISSUE THREAD

**Issue by vivekgalatage** [esprehn/chromium-codereview#98]
I received a notification about the latest stable release update for google-chrome-stable package on linux (Ubuntu 14.04). I obliged the request and my chrome is updated to the 37.0.2062.94 version.

But since this update, all the chrome review tabs are showing "404 Not Found" error.

More details from about:version:

Google Chrome   37.0.2062.94 (Official Build 290621) 
OS  Linux 
Blink   537.36 (@180557)
JavaScript  V8 3.27.34.14
Flash   14.0.0.177
User Agent  Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/37.0.2062.94 Safari/537.36
Command Line    /usr/bin/google-chrome-stable --flag-switches-begin --flag-switches-end
Executable Path /opt/google/chrome/google-chrome

**Comment by esprehn** [comment]
Please file a crbug, this is a Chrome bug that's specific to M37.
